ksw kashiwa :
	$(MAKE) -f Makefile_kashiwa

kei fx maki :
	$(MAKE) -f Makefile_kei

intel :
	$(MAKE) -f Makefile_intel

clean :
	-rm -f *.o vmc.out
	-rm -f pfapack/*.o pfapack/libpfapack.a
	-rm -f sfmt/*.o
